### ISSUE TITLE
don't assume $HOME/.config/ exists

### ISSUE THREAD

**Issue by p3ck** [CentOS-PaaS-SIG/linchpin#389]
a fresh install and new user will not have a .config directory if they never ran any other software that would create it.  linchpin should not assume it exists and create the directory if needed.

**Comment by robled** [comment]
For CI workflows, this file (and all others needed to execute linchpin successfully) should also be optionally stored/read from the linchpin workspace, as writing to `~/.config` is not compatible with CI jobs that should be self-contained.

**Comment by herlo** [comment]
@p3ck I've fixed this in my latest work. I have yet to merge it. I'll try to update this ticket when I push a new PR. Thanks

**Comment by herlo** [comment]
@robled in terms of why this exists, the runDB component cannot live in the workspace. If it does, provisioning multiple systems of the same type will not be centrally tracked. The runDB feature provides a central location for storing the database. The $HOME/.config/linchpin path is where this is stored by default, thus it must be created to accommodate this location. 

If you desire to switch it, however, it can be updated in the linchpin.conf, which can be stored in the workspace.

**Comment by herlo** [comment]
@robled you'll find this setting on line 10 of the current linchpin.conf file in the develop branch. The value is: `default_config_path = ~/.config/linchpin`. If you want to specifically change the rundb connection string, it's on line 21, which reads `rundb_conn = %(default_config_path)s/rundb-::mac::.json`. These values can be changed to whatever you'd like. Keep in mind, the `::mac::` component is used to make the database unique on a per machine basis. Feel free to tweak it and see what works for you.

**Comment by herlo** [comment]
Fixed by #398

**Comment by jaypoulz** [comment]
@herlo Running the the release1.5 candidate branch, I get the following:
```
[x86_64] + linchpin --workspace workspace --pinfile workspace/PinFile --template-data '{ arch: x86_64 }' --verbose up jenkins-slave
[x86_64] Using pinfile named 'workspace/PinFile'
[x86_64] ctx.workspace: /tmp/workspace/tiarch-ci-test-template_dev-JU5BEVQJQDO2U7Y2VYVV6NLD2RLNE6NBOV6Y7QE2OCYCR46V26PQ/workspace
[x86_64] Traceback (most recent call last):
[x86_64]   File "/usr/bin/linchpin", line 11, in <module>
[x86_64]     load_entry_point('linchpin==1.5.0rc1', 'console_scripts', 'linchpin')()
[x86_64]   File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
[x86_64]     return self.main(*args, **kwargs)
[x86_64]   File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
[x86_64]     rv = self.invoke(ctx)
[x86_64]   File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
[x86_64]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[x86_64]   File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
[x86_64]     return ctx.invoke(self.callback, **ctx.params)
[x86_64]   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
[x86_64]     return callback(*args, **kwargs)
[x86_64]   File "/usr/lib/python2.7/site-packages/click/decorators.py", line 64, in new_func
[x86_64]     return ctx.invoke(f, obj, *args[1:], **kwargs)
[x86_64]   File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
[x86_64]     return callback(*args, **kwargs)
[x86_64]   File "/usr/lib/python2.7/site-packages/linchpin/shell/__init__.py", line 207, in up
[x86_64]     return_code, results = lpcli.lp_up(targets=targets, run_id=run_id)
[x86_64]   File "/usr/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 201, in lp_up
[x86_64]     run_id=run_id)
[x86_64]   File "/usr/lib/python2.7/site-packages/linchpin/cli/__init__.py", line 343, in _execute
[x86_64]     return self.do_action(prov_data, action=action, run_id=run_id)
[x86_64]   File "/usr/lib/python2.7/site-packages/linchpin/__init__.py", line 421, in do_action
[x86_64]     rundb = self.setup_rundb()
[x86_64]   File "/usr/lib/python2.7/site-packages/linchpin/__init__.py", line 99, in setup_rundb
[x86_64]     os.mkdir(rundb_conn_dir)
[x86_64] OSError: [Errno 2] No such file or directory: '/home/jenkins/.config/linchpin'
```

I assumed this was because the 1.5 branch did not have all the patches released in 1.2, so I checked out the tag released in that branch, and merged in the release1.5 branch from there so I could ensure that I had all commits. Despite having all of the commits, this still failed.

Could you take another look into this? You can pull from my jaypoulz/release1.5 branch the version based on the tag 1.2.1.

**Comment by herlo** [comment]
@jaypoulz It looks like something happened in a commit after Nov 21 which reverted that change. I did have to do some rebasing recently. I think I can fix this by rebasing the appropriate commit. I'll let you know once I have this working again.

**Comment by herlo** [comment]
closed by #432
